### ISSUE TITLE
'Server' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by jchristensen-912** [tableau/metadata-api-samples#2]
When filling in arguments and running the sample script receive an attribute error that 'metadata' does not exist. Metadata API is enabled on server and I have all python requirements installed.

**Comment by illonage** [comment]
Hi @jchristensen-912,
Which version of Tableau Server are you using?

**Comment by jchristensen-912** [comment]
Hello @illonage! I am using 2019.3

**Comment by illonage** [comment]
If you sign in to your server and type [YOUR_SERVER_URL]/api/metadata/graphql does it work?

**Comment by jchristensen-912** [comment]
Apologies on not being specific on which sample I am referring to. I am referring to the sample [python script](https://github.com/tableau/metadata-api-samples/blob/master/samples/metadata-api-with-python-and-TSC.py). Line 51 calls server.metadata.query(query). That is the line that fails, revealing the attribute error.

**Comment by illonage** [comment]
Yes, no problems. I just want to be sure that the Metadata API works when you are directly on the server.

**Comment by jchristensen-912** [comment]
@illonage going through graphQL I am able to query just fine!

**Comment by illonage** [comment]
Which version of TSC are you using? You need the latest version 0.9: https://github.com/tableau/server-client-python/releases

**Comment by jchristensen-912** [comment]
@illonage updating the TSC worked! Thank you for your assistance! Closing this out.
